language: node_js
sudo: false
node_js:
- '0.12'
before_script:
- npm install mocha
script:
- node_modules/.bin/mocha
before_deploy:
- npm install json
- node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: jLPIskNuiXvB5ZHofLaPok9vgGAfHgFxNw0bczEtFULbQ2l+Sdo8UOSELxOrE4woY4q6BwbNsdWQoGzmLZ6qCVo/nmbCVZBM3JbUm/gUQdVdad03P5h5x8OZjQM3LqcBmewAKk4ALB0yF+gWAgSbO57Iwz92NRa/MsYbHSEuE6U=
  on:
    tags: true
    repo: DracoBlue/logging-js
    all_branches: true
    node: 0.12
