language: node_js
sudo: false
node_js:
- '0.12'
script:
- echo "no build step yet"
before_deploy:
- npm install json
- node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: j9oP+cxTL033+ELos3w7QccfzRrQ9Jxd+i8+6rF+P5xK/WsHXMfI4mbZYCV2SR8JQgGKibFzKEXkIp9BHax36HFDBjcS+ZPxzV3qVC3VVMxHRgB27p+IuvVNenFL3q+e/pTxNJCoxnkc6ffinScF16AdCSkm2CQ9f/4FoFXz0XQ=
  on:
    tags: true
    repo: DracoBlue/logging-js
    all_branches: true
    node: 0.12
